// Copyright 2019 <chaishushan{AT}gmail.com>. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//go:build ignore
// +build ignore

// Command makestatic reads a set of files and writes a Go source file to "static.go"
// that declares a map of string constants containing contents of the input files.
// It is intended to be invoked via "go generate" (directive in "gen.go").
package main

import (
	"bytes"
	"fmt"
	"os"
)

const pkgname = "nes"

var files = []struct {
	Name string
	File string
}{
	{"rom0", "BattleCity.nes"},
	{"rom1", "SuperMarioBros.nes"},
	{"rom2", "GongLuSaiChe.nes"},
	{"rom3", "HunDouLuo1_S_30.nes"},
}

func main() {
	if err := makestatic(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func makestatic() error {
	f, err := os.Create("static.wa")
	if err != nil {
		return err
	}
	defer f.Close()
	buf := new(bytes.Buffer)
	fmt.Fprintf(buf, "%v\n%v\n\n", license, warning)
	for _, fn := range files {
		b, err := os.ReadFile(fn.File)
		if err != nil {
			return err
		}
		fmt.Fprintf(buf, "global %s = [...]byte{", fn.Name)

		fmt.Fprintf(buf, " ")
		for _, v := range b {
			fmt.Fprintf(buf, "%d, ", int(v))
		}
		fmt.Fprintf(buf, "}\n\n\n")
	}

	return os.WriteFile("static.wa", buf.Bytes(), 0666)
}

// sanitize prepares a valid UTF-8 string as a raw string constant.
func sanitize(b []byte) []byte {
	// Replace ` with `+"`"+`
	b = bytes.Replace(b, []byte("`"), []byte("`+\"`\"+`"), -1)

	// Replace BOM with `+"\xEF\xBB\xBF"+`
	// (A BOM is valid UTF-8 but not permitted in Go source files.
	// I wouldn't bother handling this, but for some insane reason
	// jquery.js has a BOM somewhere in the middle.)
	return bytes.Replace(b, []byte("\xEF\xBB\xBF"), []byte("`+\"\\xEF\\xBB\\xBF\"+`"), -1)
}

const warning = `// Code generated by "makestatic"; DO NOT EDIT.`

var license = `// 版权 @2023 nes-wa 作者。保留所有权利。
`
